version: '2'
services:
    postgres:
        image: postgres:9.6.1
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=softplayer_java_apply
            - POSTGRES_USER=production
            - POSTGRES_PASSWORD=swJCwVLlHZ3R
    wildfly:
        image: lucasmattooos/softplayer-java-apply-backend-docker
        ports:
            - "80:8080"
        depends_on:
            - postgres